manager1:
  :ip:          192.168.33.20
  :enabled:     true
  :playbook:    swarm.yml
  :swarm_role:  leader
  :cpu:         1
  :memory :     1024
manager2:
  :ip:          192.168.33.21
  :enabled:     true
  :playbook:    swarm.yml
  :swarm_role:  manager
worker1:
  :ip:          192.168.33.22
  :enabled:     true
  :playbook:    swarm.yml
  :swarm_role:  worker
worker2:
  :ip:          192.168.33.23
  :enabled:     true
  :playbook:    swarm.yml
  :swarm_role:  worker
manager3:
  :ip:          192.168.33.24
  :enabled:     true
  :playbook:    swarm.yml
  :swarm_role:  manager
loadbalancer:
  :ip:          192.168.33.25
  :enabled:     true
  :playbook:    lb.yml
  :swarm_role:  load_balancer
  :memory :     512
