################################################################################
#  swarm_run Role
swarm_aux:                              # aux values used in configuration
  exposed_ports:
    microservice1:   9080
    microservice2:   9081
    microservice3:   9082
  internal_ports:
    microservice1:   8000
    microservice2:   8010
    microservice3:   8020

swarm_run:                              # microservice  example
  documentation: |
    Example of an microservice architecture with 3 services ,
    2 replicas for each.
  test:                   # This test list is run after all the services are
                          # created
                          # use --detach=false to ensure service is
                          # running
    - name:    test1      # basic testing to service1
      command: |
        curl --max-time 2 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.microservice1 }}
    - name:    test2     # sequential test in same service
      command: |
        NUMTEST=100
        TIMEOUT=0.1
        for i in {1..$NUMTEST}
        do
          curl --max-time $TIMEOUT {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.microservice1  }}
        done
  services:
    start:
      - name:     demo_microservice_1
        image:    python
        tag:      latest                     # optional image tag
        command: |
          /usr/bin/python2.7 -m  SimpleHTTPServer {{ swarm_aux.internal_ports.microservice1 }}
        options:
          --replicas 2
          --publish {{ swarm_aux.exposed_ports.microservice1 }}:{{ swarm_aux.internal_ports.microservice1 }}
          --detach=false
      - name:     demo_microservice_2
        image:    python
        tag:      latest
        command: |
          /usr/bin/python2.7 -m  SimpleHTTPServer {{ swarm_aux.internal_ports.microservice2 }}
        options:
          --replicas 2
          --publish {{ swarm_aux.exposed_ports.microservice2 }}:{{ swarm_aux.internal_ports.microservice2 }}
          --detach=false
      - name:     demo_microservice_3
        image:    python
        tag:      latest
        command: |
          /usr/bin/python2.7 -m  SimpleHTTPServer {{ swarm_aux.internal_ports.microservice3 }}
        options:
          --replicas 2
          --publish {{ swarm_aux.exposed_ports.microservice3 }}:{{ swarm_aux.internal_ports.microservice3 }}
          --detach=false
  volumes:                               # optional
    create:                              # volumes List to be created
      - name:     demo_volume_1          # volume name
        option:   "none"                 # Any option to volume creation can be specified here
      - name:     demo_volume_2
        option:   "none"
# END swarm_run  Role
################################################################################
