# local_environment group_vars


################################################################################
# Roles Configuration
################################################################################

################################################################################
#  packages Role
packages:
  upgrade: False
  remove: []
    # - "libselinux-python"
  install:
    - { name: "libselinux-python", state: "latest" }
    - { name: "bind-utils",        state: "latest" }


# END packages Role
################################################################################
################################################################################
#  firewalld Role

firewalld:
  configuration:
    input_tcp_ports:
      - { zone: "public", protocol: "tcp", port: "22"}

# END firewalld  Role
################################################################################
################################################################################
#  swarm_run Role
swarm_aux2:                              # aux values used in configuration
  exposed_ports:
    nginx1:         8080
    nginx2:         8081

swarm_aux3:                              # aux values used in configuration
  exposed_ports:
    microservice1:   9080
    microservice2:   9081
    microservice3:   9082
    microservice4:   9083
  internal_ports:
    microservice1:   2000
    microservice2:   2010
    microservice3:   2020
    microservice4:   2030

swarm_aux4:                              # aux values used in configuration
  exposed_ports:
    nginx1:         8080
    nginx2:         8081

swarm_aux: "{{ swarm_aux4 }}"

swarm_run1:                              # Generic example
  volumes:
    create:                              # define volumes here
      - name:     demo_volume_1
        option:   "none"
      - name:     demo_volume_2
        option:   "none"
  services:
    start:                              # define services here
                                        # if the service is running will not
                                        #   change anything
      - name:     demo_service_1
        image:    alpine
        tag:      latest
        command:  "ping docker.com"
        options:                             # Any service option can go here
                                             # see examples bellow
          --mount type=volume,source=demo_volume_1,destination=/tmp
          --replicas 1
          --update-delay 10s
          --update-parallelism 3
      - name:     demo_service_2
        image:    alpine
        tag:      latest
        command:  "ping docker.com"
        options:                             # Any service option can go here
          --replicas 3
      - name:     demo_service_3
        image:    alpine
        tag:      latest
        options:                             # Any service option can go here
          --replicas 1
        command:  "ping docker.com"
    # remove:                           # Define the servives to be removed
      # - name:     demo_service_3

swarm_run2:                              # nginx example
  test:
    - name:    test1
      command: "curl --max-time 1 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.nginx1 }}"
    - name:    test2
      command: "curl --max-time 1 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.nginx2 }}"
  volumes:
    create:                              # define volumes here
      - name:     demo2_volume_1
        option:   "none"
  services:                               # single service at 8080
    start:
      - name:     demo2_nginx_1
        image:    nginx
        tag:      latest
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.nginx1 }}:80       # Access service on 8080 @ any swarm host
      - name:     demo2_nginx_2
        image:    nginx
        tag:      latest
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.nginx2 }}:80       # Access service on 8081 @ any swarm host

swarm_run3:                              # microservice  example
  test:
    - name:    test1      # basic testing to each service
      command: "curl --max-time 20 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.microservice1 }}"
    - name:    test2
      command: "curl --max-time 20 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.microservice2 }}"
    - name:    test3
      command: "curl --max-time 20 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.microservice3 }}"
    - name:    test4
      command: "curl --max-time 20 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.microservice4 }}"
    - name:    test5     # sequential test in same service
      command: |
        NUMTEST=10000
        TIMEOUT=0.1
        for i in {1..$NUMTEST}
        do
          curl --max-time $TIMEOUT {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.microservice4 }}
        done
  volumes:
    create:                              # define volumes here
      - name:     demo3_volume_1
        option:   "none"
  services:
    start:
      - name:     demo3_microservice_1
        image:    python
        tag:      latest
        command: |
          python -m http.server {{ swarm_aux.internal_ports.microservice1 }}
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.microservice1}}:{{ swarm_aux.internal_ports.microservice1}}
      - name:     demo3_microservice_2
        image:    python
        tag:      latest
        command: |
          python -m http.server {{ swarm_aux.internal_ports.microservice2 }}
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.microservice2}}:{{ swarm_aux.internal_ports.microservice2}}
      - name:     demo3_microservice_3
        image:    python
        tag:      latest
        command: |
          python -m http.server {{ swarm_aux.internal_ports.microservice3 }}
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.microservice3}}:{{ swarm_aux.internal_ports.microservice3}}
      - name:     demo3_microservice_4
        image:    python
        tag:      latest
        command: |
          python -m http.server {{ swarm_aux.internal_ports.microservice4 }}
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.microservice4}}:{{ swarm_aux.internal_ports.microservice4}}

swarm_run4:                              # shared volume  example
  preconditions:
    directories:
      - "/tmp/lixo"
  test:
    - name:    test1
      command: "curl --max-time 1 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.nginx1 }}"
    - name:    test2
      command: "curl --max-time 1 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.nginx2 }}"
  volumes:
    create:                              # define volumes here
      - name:     demo4_volume_1
        option:   "none"
  services:                               # single service at 8080
    start:
      - name:     demo4_nginx_1
        image:    nginx
        tag:      latest
        options:
          --replicas 2
          --publish {{ swarm_aux.exposed_ports.nginx1 }}:80       # Access service on 8080 @ any swarm host
      - name:     demo2_nginx_1
        image:    nginx
        tag:      latest
        options:
          --replicas 2
          --publish {{ swarm_aux.exposed_ports.nginx2 }}:80       # Access service on 8081 @ any swarm host


swarm_run: "{{ swarm_run4 }}"

# Examples for service option
  # --replicas 1             Number or replicas in the swarm for the service
  # --mode global            service in each node of the cluster
  # --update-delay 10s       how often check for updates
  # --update-parallelism 3   How many concurrent updates
  # -- publish 8080:80       expose a port to ouside world and connect local port
  #                          optional protocol eg:/tcp
  #                          can be used several times
  # --env MYVAR=myvalue      set environment variable
  # --workdir /tmp           set working dir
  # --user my_user           set user
  # --mount
  #     type=volume,
  #     source=my-volume,
  #     destination=/path/in/container,
  #     volume-label="color=red",
  #     volume-label="shape=round" \

# END swarm_run  Role
################################################################################
################################################################################
# END roles Configuration
################################################################################
