# local_environment group_vars


################################################################################
# Roles Configuration
################################################################################

################################################################################
#  packages Role
packages:
  upgrade: True
  remove: []
    # - "libselinux-python"
  install:
    - { name: "libselinux-python", state: "latest" }
    - { name: "bind-utils",        state: "latest" }

# END packages Role
################################################################################
################################################################################
# END roles Configuration
################################################################################
