# local_environment group_vars


################################################################################
# Roles Configuration
################################################################################

################################################################################
#  packages Role
packages:
  upgrade: False
  remove: []
    # - "libselinux-python"
  install:
    - { name: "libselinux-python", state: "latest" }
    - { name: "bind-utils",        state: "latest" }

# END packages Role
################################################################################
################################################################################
#  firewalld Role

firewalld:
  configuration:
    input_tcp_ports:
      - { zone: "public", protocol: "tcp", port: "22"}

# END firewalld  Role
################################################################################
################################################################################
#  swarm_run Role
swarm_run:
  volumes:
    create:                              # define volumes here
      - name:     demo_volume_1
        option:   "none"
      - name:     demo_volume_2
        option:   "none"
  services:
    start:                              # define services here
                                        # if the service is running will not
                                        #   change anything
      - name:     demo_service_1
        image:    alpine
        tag:      latest
        command:  "ping docker.com"
        options:                             # Any service option can go here
                                             # see examples bellow
          --mount type=volume source=demo_volume_1 destination=/tmp
          --replicas 1
          --update-delay 10s
          --update-parallelism 3
      - name:     demo_service_2
        image:    alpine
        tag:      latest
        command:  "ping docker.com"
        options:                             # Any service option can go here
          --replicas 3
      - name:     demo_service_3
        image:    alpine
        tag:      latest
        options:                             # Any service option can go here
          --replicas 1
        command:  "ping docker.com"
    # remove:                           # Define the servives to be removed
      # - name:     demo_service_3


# Examples for service option
  # --replicas 1             Number or replicas in the swarm for the service
  # --mode global            service in each node of the cluster
  # --update-delay 10s       how often check for updates
  # --update-parallelism 3   How many concurrent updates
  # -- publish 8080:80       expose a port to ouside world and connect local port
  #                          optional protocol eg:/tcp
  #                          can be used several times
  # --env MYVAR=myvalue      set environment variable
  # --workdir /tmp           set working dir
  # --user my_user           set user
  # --mount
  #     type=volume,
  #     source=my-volume,
  #     destination=/path/in/container,
  #     volume-label="color=red",
  #     volume-label="shape=round" \

# END swarm_run  Role
################################################################################
################################################################################
# END roles Configuration
################################################################################
