# local_environment group_vars


################################################################################
# Roles Configuration
################################################################################

################################################################################
#  packages Role
packages:
  upgrade: False
  remove: []
    # - "libselinux-python"
  install:
    - { name: "libselinux-python", state: "latest" }
    - { name: "bind-utils",        state: "latest" }


# END packages Role
################################################################################
################################################################################
#  firewalld Role

firewalld:
  configuration:
    input_tcp_ports:
      - { zone: "public", protocol: "tcp", port: "22"}

# END firewalld  Role
################################################################################
################################################################################
#  swarm_run Role
swarm_aux:                              # aux values used in configuration
  exposed_ports:
    nginx1:         8080
    nginx2:         8081
    microservice1:   80

swarm_run1:                              # Generic example
  volumes:
    create:                              # define volumes here
      - name:     demo_volume_1
        option:   "none"
      - name:     demo_volume_2
        option:   "none"
  services:
    start:                              # define services here
                                        # if the service is running will not
                                        #   change anything
      - name:     demo_service_1
        image:    alpine
        tag:      latest
        command:  "ping docker.com"
        options:                             # Any service option can go here
                                             # see examples bellow
          --mount type=volume,source=demo_volume_1,destination=/tmp
          --replicas 1
          --update-delay 10s
          --update-parallelism 3
      - name:     demo_service_2
        image:    alpine
        tag:      latest
        command:  "ping docker.com"
        options:                             # Any service option can go here
          --replicas 3
      - name:     demo_service_3
        image:    alpine
        tag:      latest
        options:                             # Any service option can go here
          --replicas 1
        command:  "ping docker.com"
    # remove:                           # Define the servives to be removed
      # - name:     demo_service_3

swarm_run2:                              # nginx example
  test:
    - name:    test1
      command: "curl --max-time 1 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.nginx1 }}"
    - name:    test2
      command: "curl --max-time 1 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.nginx2 }}"
  volumes:
    create:                              # define volumes here
      - name:     demo2_volume_1
        option:   "none"
  services:                               # single service at 8080
    start:
      - name:     demo2_nginx_1
        image:    nginx
        tag:      latest
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.nginx1 }}:80       # Access service on 8080 @ any swarm host
      - name:     demo2_nginx_2
        image:    nginx
        tag:      latest
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.nginx2 }}:80       # Access service on 8081 @ any swarm host

swarm_run3:                              # microservice  example
  # test:                                  # tests that run at the end
  #   - name:    test1
  #     command: "curl --max-time 1 {{ swarm_manager_ip }}:{{ swarm_aux.exposed_ports.nginx }}"
  volumes:
    create:                              # define volumes here
      - name:     demo3_volume_1
        option:   "none"
  services:
    start:
      - name:     demo3_microservice_1
        image:    python
        tag:      latest
        command: |
          export LOG=/tmp/log1.txt
          export PORT=2000
          export WDIR=/tmp
          pushd $WDIR
          python -c "import SimpleHTTPServer
            import SocketServer
            import sys
            PORT = $PORT
            class MyHTTPHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
              log_file = open('$LOG', 'w')
              def log_message(self, format, *args):
                  self.log_file.write('%s - - [%s] %s\n' %
                            (self.client_address[0],
                             self.log_date_time_string(),
                             format%args))
              Handler = MyHTTPHandler
              httpd = SocketServer.TCPServer(('', PORT), Handler)
              print 'serving at port', PORT
              httpd.serve_forever() "
          popd
        options:
          --replicas 3
          --publish {{ swarm_aux.exposed_ports.microservice1 }}:2000       # Access service on 8080 @ any swarm host


swarm_run: "{{ swarm_run2 }}"

# Examples for service option
  # --replicas 1             Number or replicas in the swarm for the service
  # --mode global            service in each node of the cluster
  # --update-delay 10s       how often check for updates
  # --update-parallelism 3   How many concurrent updates
  # -- publish 8080:80       expose a port to ouside world and connect local port
  #                          optional protocol eg:/tcp
  #                          can be used several times
  # --env MYVAR=myvalue      set environment variable
  # --workdir /tmp           set working dir
  # --user my_user           set user
  # --mount
  #     type=volume,
  #     source=my-volume,
  #     destination=/path/in/container,
  #     volume-label="color=red",
  #     volume-label="shape=round" \

# END swarm_run  Role
################################################################################
################################################################################
# END roles Configuration
################################################################################
