# local_environment group_vars


################################################################################
# Roles Configuration
################################################################################

################################################################################
#  packages Role
packages:
  upgrade: True
  remove: []
    # - "libselinux-python"
  install:
    - { name: "libselinux-python", state: "latest" }
    - { name: "bind-utils",        state: "latest" }

# END packages Role
################################################################################
################################################################################
#  firewalld Role

firewalld:
  configuration:
    input_tcp_ports:
      - { zone: "public", protocol: "tcp", port: "22"},
      
# END firewalld  Role
################################################################################
################################################################################
# END roles Configuration
################################################################################
