# local_environment group_vars


################################################################################
# Roles Configuration
################################################################################

################################################################################
#  base Role
base:
  configuration:
    # repo_base_url:  "http://{{ endpoints.repo.server_name }}/" # if not defined
    #                                                            # will not be
    #                                                            # used
  install_packages:
    - { name: "libselinux-python", state: "latest" }
    - { name: "bind-utils",        state: "latest" }
  command_tests:
    - {
        name:        "dummy test",
        become_user: "root",
        command:     "echo"
      }

# END base Role
################################################################################
################################################################################
#  firewall Role
firewall:
  configuration:
    input_tcp_ports:
      - { zone: "public", protocol: "tcp", port: "22"} # ensure ssh is open
# END firewall Role
################################################################################

################################################################################
# END roles Configuration
################################################################################
