# local_environment group_vars


################################################################################
# Roles Configuration
################################################################################

################################################################################
#  swarm_run Role

#- include: "example4.yml"

# END swarm_run  Role
################################################################################
################################################################################
# END roles Configuration
################################################################################
