# local_environment_group_swarm group_vars


################################################################################
# Roles Configuration
################################################################################
################################################################################
#  firewalld Role

firewalld:
  configuration:
    input_ports:
      - { zone: "public", protocol: "tcp", port: "22"}
      - { zone: "public",
          protocol: "tcp",
          port: "1-65535",
          source: "{{ swarm_network }}"
        }
    extra_ports : []

# END firewalld  Role
################################################################################

################################################################################
# END roles Configuration
################################################################################
