#
# Common Provision
- hosts:
    - leader_group
    - others_group
  roles:
     - { role: ajsalminen.hosts } #, hosts_additional_hosts:  add_hosts | default ([]) }
     - ansible_repos
     - ansible_packages
     - { role: ansible_firewalld }
     - ansible_docker_ce_centos_install

#
# Provision leader
- hosts:
    - leader_group
  roles:
     - ansible_docker_swarm_leader

#
# Provision other managers and workers
- hosts:
    - others_group
  roles:
     - ansible_docker_swarm_node
