#
# Setup
- hosts: all
  tasks:
    - name: Gather Facts
      setup:

#
# Provision
- hosts:
    - worker_servers
  roles:
     - { role: ajsalminen.hosts } 
     - base
     - { role: firewalld,
         extra_ports : [
           { zone: "public", protocol: "tcp", port: "2377"},
           { zone: "public", protocol: "tcp", port: "7946"},
           { zone: "public", protocol: "udp", port: "7946"},
           { zone: "public", protocol: "udp", port: "4789"}
         ]
        }
     - docker_ce_centos_install
