# local_environment_group_all group_vars


################################################################################
# Roles Configuration
################################################################################

# ################################################################################
# #  packages Role
packages:
  yum:
    upgrade: False
    remove: []
      # - "libselinux-python"
    install:
      - { name: "libselinux-python",   state: "latest" }
      - { name: "selinux-policy-base", state: "latest" }
      - { name: "bind-utils",          state: "latest" }
      - { name: "net-tools",           state: "latest" }
  apt:
    remove:
      - "some-stupid-package"
    upgrade: False
    install:
      - { name: "wget",   state: "latest" }
  tests:
    - {
        name: test1,
        command: "echo 'test1 succeed' "
      }
    - {
        name: test2,
        command: "echo 'test2 succeed' "
      }


#
# # END packages Role
# ################################################################################
################################################################################
# repos  Role
repos:
  key_list: []                          # list of repository keys to import
    # - "http://packages.elastic.co/GPG-KEY-elasticsearch"
  package_list: []                      # Optional list of packages to install .
  #                                       # optionally  with version (default to latest )
  # - { name: "bind-utils",        state: "latest" }
  names_to_remove:                      # Optional - List of repos definition to remove
    - repo2.repo
    - repo3.repo
  add:                                  # Also optional - list of repos to create
    - name: repo1
      content: |
       [custom_repo]
       name=Ansible repo build by ansible
       mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
       gpgcheck=1
       gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
# END repos  Role
################################################################################

################################################################################
# END roles Configuration
################################################################################
